// <auto-generated />
using Employees.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Employees.Migrations
{
    [DbContext(typeof(EmployeesDbContext))]
    [Migration("20230809005435_Initial create")]
    partial class Initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Employees.Models.Oddeli", b =>
                {
                    b.Property<int>("OddelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OddelId"), 1L, 1);

                    b.Property<int>("BrojVraboteni")
                        .HasColumnType("int");

                    b.Property<string>("ImeOddel")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("OddelId");

                    b.ToTable("Oddeli");
                });

            modelBuilder.Entity("Employees.Models.Vraboteni", b =>
                {
                    b.Property<int>("VrabotenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VrabotenId"), 1L, 1);

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("OddelId")
                        .HasColumnType("int");

                    b.Property<decimal>("Plata")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("VrabotenId");

                    b.ToTable("Vraboteni");
                });
#pragma warning restore 612, 618
        }
    }
}
